name: build-and-publish-artifact

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifacturl: ${{ steps.artifact-upload-step.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@v3
      - name: Build package
        run: |
          dotnet restore FlightFinder.sln
          dotnet build FlightFinder.sln
      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: dotnet-binary
          path: ./FlightFinder.Server/FlightFinder.Server.csproj
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # - name: Download artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: dotnet-binary
      #     path: ./download
      - name: Get Artifact URL
        run: |
          echo "Pre fetch directory listing"
          ls -al
          find .
          echo "Artifact URL from previous job is $ARTIFACTURL"
          echo "Attempting to fetch artifact"
          curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L -o artifact.zip "{$ARTIFACTURL}/zip" 
          echo "Now listing the directory contents"
          ls -al
          find .
        env:
          ARTIFACTURL: ${{needs.build.outputs.artifacturl}}
