name: build-and-publish-artifact

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifacturl: ${{ steps.artifact-upload-step.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@v3
      - name: Build package
        run: |
          dotnet restore FlightFinder.sln
          dotnet build FlightFinder.sln
      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: dotnet-binary
          path: \FlightFinder.Server\FlightFinder.Server.csproj
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get Artifact URL
        run: echo "Artifact URL from previous job is $ARTIFACTURL"
        env:
          ARTIFACTURL: ${{needs.build.outputs.artifacturl}}
