name: build-and-publish-artifact

on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # outputs:
    #   output1: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
      - name: Build package
        run: |
          dotnet restore FlightFinder.sln
          dotnet build FlightFinder.sln
          ls -al
  #     - uses: actions/upload-artifact@v4
  #       id: artifact-upload-step
  #       with:
  #       name: my-artifact
  #       path: path/to/artifact/content/
  # job2:
  #   runs-on: ubuntu-latest
  #   needs: job1
  #   steps:
  #     - env:
  #       OUTPUT1: ${{needs.job1.outputs.output1}}
  #     run: echo "Artifact ID from previous job is $OUTPUT1"